name: Flet Multiplatform Build (Windows, macOS, APK, IPA)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows:
    name: Build Windows Executable
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Flet and PyInstaller
        run: |
          python -m pip install --upgrade pip
          pip install flet pyinstaller
      - name: Build EXE
        run: |
          pyinstaller --onefile --windowed --name MyFletApp main.py

  build-macos:
    name: Build macOS App
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Flet and PyInstaller
        run: |
          python -m pip install --upgrade pip
          pip install flet pyinstaller
      - name: Build macOS App
        run: |
          pyinstaller --onefile --windowed --name MyFletApp main.py

  build-android-apk:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Flet and Buildozer dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake
          pip install flet buildozer cython==0.29.36 virtualenv
      - name: Initialize Buildozer
        run: |
          buildozer init
          echo "requirements = flet==0.18.0, pyjnius" >> buildozer.spec
          echo "orientation = portrait" >> buildozer.spec
      - name: Build APK
        run: |
          buildozer -v android debug

  build-ios-ipa:
    name: Build iOS IPA (Requires Apple Developer Account)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install Flet and Kivy
        run: |
          python -m pip install --upgrade pip
          pip install flet kivy
      - name: Build IPA (iOS)
        run: |
          echo "iOS builds require Xcode and Apple Developer Account"
          # يمكنك إضافة خطوات بناء iOS هنا إذا كان لديك شهادة مطور Apple
